# https://dart.dev/tools/pub/pubspec

name: finch
version: 0.0.0-dev
description: Opinionated workflow and tooling for hacking on the Flutter engine
repository: https://github.com/matanlurey/finch
issue_tracker: https://github.com/matanlurey/finch/issues

environment: 
  sdk: ^3.3.0

executables:
  finch: main

dependencies:
  args: ^2.4.2
  async: ^2.11.0
  collection: ^1.18.0
  http: ^1.2.1
  meta: ^1.12.0
  path: ^1.9.0
  stack_trace: ^1.11.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
